### ISSUE TITLE
Icon request: "help" and "warning"

### ISSUE THREAD

**Issue by henrikfalck** [astrit/css.gg#101]
Seeing as we've already got the [`info` icon](https://css.gg/info) it seems only fitting that there should also be icons for `help`/`question` and `warning`, which is pretty common to use in a UI.

**Comment by Awin-G** [comment]
There is an icon called danger that can express a warning.
But I prefer symbols like the triangle that have edges and a warning connotation. So I redesigned one based on the triangle icon:

<img width="428" height="356" alt="Image" src="https://github.com/user-attachments/assets/e9e9dd1d-e522-435e-b433-a1066eb17b2b" />

```scss
.gg-shape-triangle {
  position: relative;
  transform: scale(var(--ggs, 1));
  width: 22px;
  height: 20px;
  border-left: 2px solid transparent;
  border-bottom: 2px solid currentColor;
}
.gg-shape-triangle,
.gg-shape-triangle::before {
  display: block;
  box-sizing: border-box;
  border-right: 3px solid transparent;
}
.gg-shape-triangle::before {
  content: "";
  position: absolute;
  width: 22px;
  height: 22px;
  border-left: 2px solid currentColor;
  border-top: 2px solid currentColor;
  border-bottom: 2px solid transparent;
  transform: rotate(45deg) skew(15deg, 15deg);
  left: -2.5px;
  bottom: -13px;
}
.gg-shape-triangle::after {
  // -------plan A: use "!"--------
  // content: "!";
  // position: absolute;
  // left: 6.7px;
  // top: 1.7px;
  // font-size: 12px;
  // font-family: 'Times New Roman', Times, serif;
  content: "";

  // -------plan B: use border--------
  position: absolute;
  width: 1px;
  height: 2px;
  left: 8px;
  top: 8px;
  border-top: 5px solid currentColor;
  border-left: -3px solid transparent;
  border-bottom: 1px solid currentColor;
}

```
