### ISSUE TITLE
bootstrap button with css.gg icon not in one line

### ISSUE THREAD

**Issue by shaozi** [astrit/css.gg#32]
When I do this:

```html
<button class="btn btn-primary btn-block">
        A button <span class="gg-sort-az"></span>
    </button>
```
the icon is moved to a new line. Like this:

```text
+---------------------------------------------------------------+
|                         A button                              |
|  [icon]                                                       |
+---------------------------------------------------------------+
```

I am expecting this:

```text
+---------------------------------------------------------------+
|                   A button   [icon]                           |
+---------------------------------------------------------------+
```

**Comment by astrit** [comment]
@shaozi

Add flex class to the button like this: 
```html
<div class="btn btn-primary d-flex align-items-center">
      A button <span class="gg-sort-az"></span>
</div>
```

**Comment by shaozi** [comment]
But what about in a div or p element? I cannot put flexbox everywhere.
Why it is display as block not inline anyway?

**Comment by astrit** [comment]
This is designed to be as standalone as possible, you can create a class and add it to every icon where you need and overwrite the display, or you can 

```css
 [class^="gg-"] {
   display: inline-flex; 
}
```

**Comment by shaozi** [comment]
Is there an easy way to unify all their size (same height) and alignment (align center)?
![Screen Shot 2020-05-02 at 2 47 28 PM](https://user-images.githubusercontent.com/417833/80887916-db88c700-8c83-11ea-8217-b8a8b734d0c9.png)

**Comment by astrit** [comment]
Yes, you can just create a div with class `.icon-wrapper` and then do t he following 

```css
    .icon-wrapper {
        display: flex;
        justify-content: center;
        align-items: center;
        width: 24px;
        height: 24px;
    }
```

And then your markup would look like: 
```html
    <div class="icon-wrapper>
          <i class="gg-add"></i>
    </div>
```

Also you can use the SVG version if don't like doing it with CSS.
